### ISSUE TITLE
Peer review

### ISSUE THREAD

**Issue by SalvatoreAdalberto** [Xiusss/Computational_Intelligence#1]
**Majors**
- The choice of the algorithm is not the best possible because the goal of the task was to find the optimal solution minimizing the number of visited nodes, while Breadth-First Search guarantees finding the optimal solution by visiting all possible nodes.

**Minors**
- In this solution the existence of a solution is guaranteed by the greedy algorithm finding a solution, in my opinion this is not so efficient. It would have been enough to create a set with all the elements of all lists comparing its length with N, in fact this can be also done in one line.
- The solution is written in C-style, a more pythonic way would have saved a lot of lines

**Comment by Xiusss** [comment]
Thanks for the review!

Majors:

- We got that and were thinking about A* search. Any suggestion about that?

Minors:

- It may be. I think that the efficiency of the greedy algorithm is quite fine, stated that it's 'greedy' and the compromise on the optimality should make it computationally efficient enough.

- For almost everyone in my group is the first time approaching python so it will need some time to completely switch to python in every detail!

Thank you very much for your comments!
